<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNtr4vrc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNtr4vrc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNtr4vrc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNtr4vrc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNtr4vrc\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ntr4vrc',
    'container.build_id' => '932002d7',
    'container.build_time' => 1516094448,
));
