<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVq2hwil\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVq2hwil/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVq2hwil.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVq2hwil\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVq2hwil\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vq2hwil',
    'container.build_id' => 'f8007cf7',
    'container.build_time' => 1516040622,
));
